### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by alkondrashov** [PragmaticFlow/NBomber.Http#3]

**Comment by alkondrashov** [comment]
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, Int32 hashcode, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.FSharp.Core.PrintfImpl.Cache`4.Get(PrintfFormat`4 key)
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThen[T](PrintfFormat`4 format)
   at Executable.parseCommandLineRec(FSharpList`1 args, CommandLineOptions optionsSoFar)
   at Executable.parseCommandLine(FSharpList`1 args)
   at Executable.main(String[] argv)
Abort trap: 6
```

**Comment by alkondrashov** [comment]
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Executable.parseCommandLineRec(FSharpList`1 args, CommandLineOptions optionsSoFar)
   at Executable.parseCommandLine(FSharpList`1 args)
   at Executable.main(String[] argv)
Abort trap: 6
```
